apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 7
  selector:
    name: proxy
  template:
    metadata:
      name: nginx
      labels:
        name: "proxy"
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
